version: 2
jobs:
  build:
    working:
    working_directory: ~/myapp
    docker:
       - image: circleci/mode:8-browsers
    steps:
       - checkout:
       path: ~/myapp
       - restore_cache:
       key: angular-wishlist-{{.Branch}}-{{checksum "package-lock.json"}}
       - run: npm install 
       - save_cache:
       key: angular-wishlist-{{.Branch}}-{{checksum "package-lock.json"}}
       paths:
       - "node_modules"
       - run: npm run test -- -- progress=false --watch=false --browser=ChromeHeadlessCI
       